### index
GET http://localhost:8080/api/discounts?page=1&per_page=5
Accept: application/json
Authorization: Bearer my-secret-token

### show
GET http://localhost:8080/api/discounts/1
Authorization: Bearer my-secret-token

### create
POST http://localhost:8080/api/discounts
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "tanggal": "2026-08-01",
  "nominal": 175000
}

### create - gagal (tanggal duplikat / tidak boleh sama)
POST http://localhost:8080/api/discounts
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "tanggal": "2026-08-01",
  "nominal": 200000
}

### update all field
PUT http://localhost:8080/api/discounts/11
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "tanggal": "2026-08-01",
  "nominal": 500000
}

### update some field
PATCH http://localhost:8080/api/discounts/11
Authorization: Bearer my-secret-token
Content-Type: application/json

{
  "nominal": 250000
}

### delete
DELETE http://localhost:8080/api/discounts/11
Authorization: Bearer my-secret-token
